const actions = {
  CHECK_SESSION: 'CHECK_SESSION',
  LOG_IN: 'LOG_IN',
  CREATE_USER: 'CREATE_USER',
  GET_MEDIA: 'GET_MEDIA',
  ADD_MEDIA: 'ADD_MEDIA',
  UPDATE_MEDIA: 'UPDATE_MEDIA',
  DELETE_MEDIA: 'DELETE_MEDIA',
  UPDATE_SELECTED_MEDIA_TYPE: 'UPDATE_SELECTED_MEDIA_TYPE'
}

export default actions;